=== AmoVanB/master-thesis/centralized/config/config.dtd
<!ELEMENT config (log,update,domain,rules?)>
<!ELEMENT log EMPTY>
  <!ATTLIST log level CDATA #REQUIRED>
<!ELEMENT update EMPTY>
  <!ATTLIST update rate CDATA #REQUIRED>
<!ELEMENT domain EMPTY>
  <!ATTLIST domain name CDATA #REQUIRED>
<!ELEMENT rules (rule+)>
<!ELEMENT rule (#PCDATA)>
  <!ATTLIST rule src-address       CDATA #REQUIRED>
  <!ATTLIST rule src-prefix-length CDATA #REQUIRED>
  <!ATTLIST rule router            CDATA #REQUIRED>
  <!ATTLIST rule name              CDATA #REQUIRED>
  <!ATTLIST rule type              CDATA #REQUIRED>

=== AmoVanB/master-thesis/centralized/config/config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config>
  <log level="debug"/>
  <update rate="10"/>
  <domain name="amo.vyncke.org"/>
  <rules>
    <rule src-address="2001:db8:0:85a3::ac1f:8001" src-mask="12" name=".*Room.*" type=".*" router="london">allow</rule>
    <rule src-address="2015:db8:0:85a3::ac1f:8001" src-mask="22" name=".*Desk.*" type=".*" router="brussels">allow</rule>
    <rule src-address="1993:db8:0:85a3::ac1f:8001" src-mask="11" name=".*" type=".*" router="*">deny</rule>
  </rules>
</config>
