=== AmoVanB/master-thesis/local/config/config.dtd
<!ELEMENT config (log,database,domain,ip*,interface*,rules?)>
<!ELEMENT log EMPTY>
  <!ATTLIST log level CDATA #REQUIRED>
<!ELEMENT database EMPTY>
  <!ATTLIST database user     CDATA #REQUIRED>
  <!ATTLIST database password CDATA #REQUIRED>
  <!ATTLIST database name     CDATA #REQUIRED>
  <!ATTLIST database host     CDATA #REQUIRED>
  <!ATTLIST database socket   CDATA #REQUIRED>
  <!ATTLIST database port     CDATA #REQUIRED>
<!ELEMENT domain EMPTY>
  <!ATTLIST domain server    CDATA #REQUIRED>
  <!ATTLIST domain zone      CDATA #REQUIRED>
  <!ATTLIST domain keyname   CDATA #REQUIRED>
  <!ATTLIST domain keyvalue  CDATA #REQUIRED>
  <!ATTLIST domain algorithm CDATA #REQUIRED>
  <!ATTLIST domain ttl       CDATA #REQUIRED>
<!ELEMENT ip EMPTY>
  <!ATTLIST ip version CDATA #REQUIRED>
  <!ATTLIST ip alias   CDATA #REQUIRED>
<!ELEMENT interface EMPTY>
  <!ATTLIST interface name  CDATA #REQUIRED>
  <!ATTLIST interface alias CDATA #REQUIRED>
<!ELEMENT rules (service+)>
<!ELEMENT service (#PCDATA)>
  <!ATTLIST service name           CDATA #REQUIRED>
  <!ATTLIST service type           CDATA #REQUIRED>
  <!ATTLIST service interface-name CDATA #REQUIRED>
  <!ATTLIST service interface-ip   CDATA #REQUIRED>
  <!ATTLIST service hostname       CDATA #REQUIRED>
  <!ATTLIST service port           CDATA #REQUIRED>

=== AmoVanB/master-thesis/decentralized/config/config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config name="brussels" alias=" @ Brussels" public-interfaces="eth0">
  <log level="info" />
  <database user="amo"
            password="cisco123"            
            name="service_discovery"
            host="localhost" 
            socket="/opt/lampp/var/mysql/mysql.sock"  
            port="3306"/> 
  <domain server="ks.vyncke.org"              
          zone="amo.vyncke.org"               
          keyname="amoupdate."                
          keyvalue="BK1wQkLhDySTEMhLDeDSdg==" 
          algorithm="HMAC_MD5"                
          ttl="60" />
  <ip version="4" alias=":v4]" />
  <ip version="6" alias=":v6]" />
  <interface name="eth2" alias=" [IT" />
  <interface name="eth1" alias=" [Sales" />
  <rules>
    <!-- Allow IPP services and services announced on IPv6. -->
    <service name=".*" type="_ipp\._tcp" interface-name=".*"  
             interface-ip=".*" hostname=".*" port=".*">allow</service>
    <service name=".*" type=".*" interface-name=".*"  
             interface-ip="6" hostname=".*" port=".*">allow</service>
    <service name=".*" type=".*" interface-name=".*"  
             interface-ip=".*" hostname=".*" port=".*">deny</service>
  </rules>
</config>

=== AmoVanB/master-thesis/local/config/config.xml
<?xml version="1.0"?>
<!DOCTYPE config SYSTEM "config.dtd">
<config name="home" alias="" public-interfaces="wlp4s0">
  <log level="info" />
  <database user="amo" password="cisco123"            
            name="service_discovery" host="localhost" 
            socket="/opt/lampp/var/mysql/mysql.sock"  
            port="3306"/> 
  <domain server="ks.vyncke.org"              
          zone="amo.vyncke.org"               
          keyname="amoupdate."                
          keyvalue="BK1wQkLhDySTEMhLDeDSdg==" 
          algorithm="HMAC_MD5"                
          ttl="5" />
  <ip version="4" alias=" IPv4)" />
  <ip version="6" alias=" IPv6)" />
  <interface name="wlp4s0" alias="(Wifi" />
  <interface name="p5p1" alias="(Ethernet" />
  <rules>
    <service name=".*" type="_ipp\._tcp" interface-name=".*"  
             interface-ip=".*" hostname=".*" port=".*">
      allow
    </service>
    <service name=".*" type=".*" interface-name=".*"  
             interface-ip=".*" hostname=".*" port=".*">
      deny
    </service>
  </rules>
</config>
